const menu = [
  {
    id: 1,
    title: "banana and oat pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpg",
    desc: `Acestea sunt denumite "Pancakes sanatoase". De ce sanatoase? Pentru ca nu au zahar, nu au ulei, nu au faina alba. Iti dau insa energie si tot ce ai tu nevoie pentru o zi plina si extenuanta. `,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Un hamburger perfect, pentru o persoana infometata. O explozie de gusturi care merita incercata `,
  },
  {
    id: 3,
    title: "strawberries milkshake ",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpg",
    desc: `Milshake cu capsune este o reteta nu doar pentru o seara lenesa si relaxata dupa 5 zile de vacanta, dar si o reteta de inceput de vacanta. Este reteta perefecta pentru o vara lunga si calda, pentru ca un milkshake cu capsune racoreste pana si cele mai toride zile!`,
  },
  {
    id: 4,
    title: "benedict eggs",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpg",
    desc: ` Oua Benedict! Ce sunt ouale astea Benedict pe care le vedem in meniurile de breakfast din restaurante, bistro-uri si cafenele? Sunt un preparat extraodinar de gustos – o briosa englezeasca, felii de sunca, ou posat si un foarte fin sos olandez care completeaza totul! `,
  },
  {
    id: 5,
    title: "egg hamburger",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Hamburger cu omleta - o combinatie excelenta pentru imbinarea micului dejun cu un cheat day `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Acest milkshake Oreo este unul dintre preferatele noastre, se prepara rapid si este o placere pentru copii`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Pentru pasionatii de bacon prajit,  va invitam sa gustati din hamburgerul nostru pentru a incepe ziua cu energie si determinare `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Ahoi Captain America ! Daca va doriti un clasic, va sugeram sa incercati hamburgerul nostru de toate zilele in stil american `,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-10.jpeg",
    desc: `Carantina din ultima vreme nu ne va impiedica niciodata sa ne bucuram impreuna de aromele bogate ale unui milkshake cu lapte si frisca.`,
  },
];
export default menu;
